package com.example.capstoneapplication

/**
 * This is the class for generating elements
 */
class ElementFactory {
    /**
     * This method generates the new element
     * @param atomicnum - number of the element
     * @return - returns the new element
     */
    fun numberfactory(atomicnum: Int): Elements? {
        when (atomicnum) {
            (1) -> return Hydrogen()
            (2) -> return Helium()
            (3) -> return Lithium()
            (4) -> return Beryllium()
            (5) -> return Boron()
            (6) -> return Carbon()
            (7) -> return Nitrogen()
            (8) -> return Oxygen()
            (9) -> return Fluorine()
            (10) -> return Neon()
            (11) -> return Sodium()
            (12) -> return Magnesium()
            (13) -> return Aluminum()
            (14) -> return Silicon()
            (15) -> return Phosphorus()
            (16) -> return Sulfur()
            (17) -> return Chlorine()
            (18) -> return Argon()
            (19) -> return Potassium()
            (20) -> return Calcium()
            (21) -> return Scandium()
            (22) -> return Titanium()
            (23) -> return Vanadium()
            (24) -> return Chromium()
            (25) -> return Manganese()
            (26) -> return Iron()
            (27) -> return Cobalt()
            (28) -> return Nickel()
            (29) -> return Copper()
            (30) -> return Zinc()
            (31) -> return Gallium()
            (32) -> return Germanium()
            (33) -> return Arsenic()
            (34) -> return Selenium()
            (35) -> return Bromine()
            (36) -> return Krypton()
            (37) -> return Rubidium()
            (38) -> return Strontium()
            (39) -> return Yttrium()
            (40) -> return Zirconium()
            (41) -> return Niobium()
            (42) -> return Molybdenum()
            (43) -> return Technetium()
            (44) -> return Ruthenium()
            (45) -> return Rhodium()
            (46) -> return Palladium()
            (47) -> return Silver()
            (48) -> return Cadmium()
            (49) -> return Indium()
            (50) -> return Tin()
            (51) -> return Antimony()
            (52) -> return Tellurium()
            (53) -> return Iodine()
            (54) -> return Xenon()
            (55) -> return Cesium()
            (56) -> return Barium()
            (57) -> return Lanthanum()
            (58) -> return Cerium()
            (59) -> return Praseodymium()
            (60) -> return Neodymium()
            (61) -> return Promethium()
            (62) -> return Samarium()
            (63) -> return Europium()
            (64) -> return Gadolinium()
            (65) -> return Terbium()
            (66) -> return Dysprosium()
            (67) -> return Holmium()
            (68) -> return Erbium()
            (69) -> return Thulium()
            (70) -> return Ytterbium()
            (71) -> return Lutetium()
            (72) -> return Hafnium()
            (73) -> return Tantalum()
            (74) -> return Tungsten()
            (75) -> return Rhenium()
            (76) -> return Osmium()
            (77) -> return Iridium()
            (78) -> return Platinum()
            (79) -> return Gold()
            (80) -> return Mercury()
            (81) -> return Thallium()
            (82) -> return Lead()
            (83) -> return Bismuth()
            (84) -> return Polonium()
            (85) -> return Astatine()
            (86) -> return Radon()
            (87) -> return Francium()
            (88) -> return Radium()
            (89) -> return Actinium()
            (90) -> return Thorium()
            (91) -> return Protactinium()
            (92) -> return Uranium()
            (93) -> return Neptunium()
            (94) -> return Plutonium()
            (95) -> return Americium()
            (96) -> return Curium()
            (97) -> return Berkelium()
            (98) -> return Californium()
            (99) -> return Einsteinium()
            (100) -> return Fermium()
            (101) -> return Mendelevium()
            (102) -> return Nobelium()
            (103) -> return Lawrencium()
            (104) -> return Rutherfordium()
            (105) -> return Dubnium()
            (106) -> return Seaborgium()
            (107) -> return Bohrium()
            (108) -> return Hassium()
            (109) -> return Meitnerium()
            (110) -> return Darmstadtium()
            (111) -> return Roentgenium()
            (112) -> return Copernicium()
            (113) -> return Nihonium()
            (114) -> return Flerovium()
            (115) -> return Moscovium()
            (116) -> return Livermorium()
            (117) -> return Tennessine()
            (118) -> return Oganesson()
            else -> return null
        }
    }

    fun stringfactory(atomicnum: String): Elements? {
        when (atomicnum) {
            ("com.example.capstoneapplication.Hydrogen") -> return Hydrogen()
            ("com.example.capstoneapplication.Helium") -> return Helium()
            ("com.example.capstoneapplication.Lithium") -> return Lithium()
            ("com.example.capstoneapplication.Beryllium") -> return Beryllium()
            ("com.example.capstoneapplication.Boron") -> return Boron()
            ("com.example.capstoneapplication.Carbon") -> return Carbon()
            ("com.example.capstoneapplication.Nitrogen") -> return Nitrogen()
            ("com.example.capstoneapplication.Oxygen") -> return Oxygen()
            ("com.example.capstoneapplication.Fluorine") -> return Fluorine()
            ("com.example.capstoneapplication.Neon") -> return Neon()
            ("com.example.capstoneapplication.Sodium") -> return Sodium()
            ("com.example.capstoneapplication.Magnesium") -> return Magnesium()
            ("com.example.capstoneapplication.Aluminum") -> return Aluminum()
            ("com.example.capstoneapplication.Silicon") -> return Silicon()
            ("com.example.capstoneapplication.Phosphorus") -> return Phosphorus()
            ("com.example.capstoneapplication.Sulfur") -> return Sulfur()
            ("com.example.capstoneapplication.Chlorine") -> return Chlorine()
            ("com.example.capstoneapplication.Argon") -> return Argon()
            ("com.example.capstoneapplication.Potassium") -> return Potassium()
            ("com.example.capstoneapplication.Calcium") -> return Calcium()
            ("com.example.capstoneapplication.Scandium") -> return Scandium()
            ("com.example.capstoneapplication.Titanium") -> return Titanium()
            ("com.example.capstoneapplication.Vanadium") -> return Vanadium()
            ("com.example.capstoneapplication.Chromium") -> return Chromium()
            ("com.example.capstoneapplication.Manganese") -> return Manganese()
            ("com.example.capstoneapplication.Iron") -> return Iron()
            ("com.example.capstoneapplication.Cobalt") -> return Cobalt()
            ("com.example.capstoneapplication.Nickel") -> return Nickel()
            ("com.example.capstoneapplication.Copper") -> return Copper()
            ("com.example.capstoneapplication.Zinc") -> return Zinc()
            ("com.example.capstoneapplication.Gallium") -> return Gallium()
            ("com.example.capstoneapplication.Germanium") -> return Germanium()
            ("com.example.capstoneapplication.Arsenic") -> return Arsenic()
            ("com.example.capstoneapplication.Selenium") -> return Selenium()
            ("com.example.capstoneapplication.Bromine") -> return Bromine()
            ("com.example.capstoneapplication.Krypton") -> return Krypton()
            ("com.example.capstoneapplication.Rubidium") -> return Rubidium()
            ("com.example.capstoneapplication.Strontium") -> return Strontium()
            ("com.example.capstoneapplication.Yttrium") -> return Yttrium()
            ("com.example.capstoneapplication.Zirconium") -> return Zirconium()
            ("com.example.capstoneapplication.Niobium") -> return Niobium()
            ("com.example.capstoneapplication.Molybdenum") -> return Molybdenum()
            ("com.example.capstoneapplication.Technetium") -> return Technetium()
            ("com.example.capstoneapplication.Ruthenium") -> return Ruthenium()
            ("com.example.capstoneapplication.Rhodium") -> return Rhodium()
            ("com.example.capstoneapplication.Palladium") -> return Palladium()
            ("com.example.capstoneapplication.Silver") -> return Silver()
            ("com.example.capstoneapplication.Cadmium") -> return Cadmium()
            ("com.example.capstoneapplication.Indium") -> return Indium()
            ("com.example.capstoneapplication.Tin") -> return Tin()
            ("com.example.capstoneapplication.Antimony") -> return Antimony()
            ("com.example.capstoneapplication.Tellurium") -> return Tellurium()
            ("com.example.capstoneapplication.Iodine") -> return Iodine()
            ("com.example.capstoneapplication.Xenon") -> return Xenon()
            ("com.example.capstoneapplication.Cesium") -> return Cesium()
            ("com.example.capstoneapplication.Barium") -> return Barium()
            ("com.example.capstoneapplication.Lanthanum") -> return Lanthanum()
            ("com.example.capstoneapplication.Cerium") -> return Cerium()
            ("com.example.capstoneapplication.Praseodymium") -> return Praseodymium()
            ("com.example.capstoneapplication.Neodymium") -> return Neodymium()
            ("com.example.capstoneapplication.Promethium") -> return Promethium()
            ("com.example.capstoneapplication.Samarium") -> return Samarium()
            ("com.example.capstoneapplication.Europium") -> return Europium()
            ("com.example.capstoneapplication.Gadolinium") -> return Gadolinium()
            ("com.example.capstoneapplication.Terbium") -> return Terbium()
            ("com.example.capstoneapplication.Dysprosium") -> return Dysprosium()
            ("com.example.capstoneapplication.Holmium") -> return Holmium()
            ("com.example.capstoneapplication.Erbium") -> return Erbium()
            ("com.example.capstoneapplication.Thulium") -> return Thulium()
            ("com.example.capstoneapplication.Ytterbium") -> return Ytterbium()
            ("com.example.capstoneapplication.Lutetium") -> return Lutetium()
            ("com.example.capstoneapplication.Hafnium") -> return Hafnium()
            ("com.example.capstoneapplication.Tantalum") -> return Tantalum()
            ("com.example.capstoneapplication.Tungsten") -> return Tungsten()
            ("com.example.capstoneapplication.Rhenium") -> return Rhenium()
            ("com.example.capstoneapplication.Osmium") -> return Osmium()
            ("com.example.capstoneapplication.Iridium") -> return Iridium()
            ("com.example.capstoneapplication.Platinum") -> return Platinum()
            ("com.example.capstoneapplication.Gold") -> return Gold()
            ("com.example.capstoneapplication.Mercury") -> return Mercury()
            ("com.example.capstoneapplication.Thallium") -> return Thallium()
            ("com.example.capstoneapplication.Lead") -> return Lead()
            ("com.example.capstoneapplication.Bismuth") -> return Bismuth()
            ("com.example.capstoneapplication.Polonium") -> return Polonium()
            ("com.example.capstoneapplication.Astatine") -> return Astatine()
            ("com.example.capstoneapplication.Radon") -> return Radon()
            ("com.example.capstoneapplication.Francium") -> return Francium()
            ("com.example.capstoneapplication.Radium") -> return Radium()
            ("com.example.capstoneapplication.Actinium") -> return Actinium()
            ("com.example.capstoneapplication.Thorium") -> return Thorium()
            ("com.example.capstoneapplication.Protactinium") -> return Protactinium()
            ("com.example.capstoneapplication.Uranium") -> return Uranium()
            ("com.example.capstoneapplication.Neptunium") -> return Neptunium()
            ("com.example.capstoneapplication.Plutonium") -> return Plutonium()
            ("com.example.capstoneapplication.Americium") -> return Americium()
            ("com.example.capstoneapplication.Curium") -> return Curium()
            ("com.example.capstoneapplication.Berkelium") -> return Berkelium()
            ("com.example.capstoneapplication.Californium") -> return Californium()
            ("com.example.capstoneapplication.Einsteinium") -> return Einsteinium()
            ("com.example.capstoneapplication.Fermium") -> return Fermium()
            ("com.example.capstoneapplication.Mendelevium") -> return Mendelevium()
            ("com.example.capstoneapplication.Nobelium") -> return Nobelium()
            ("com.example.capstoneapplication.Lawrencium") -> return Lawrencium()
            ("com.example.capstoneapplication.Rutherfordium") -> return Rutherfordium()
            ("com.example.capstoneapplication.Dubnium") -> return Dubnium()
            ("com.example.capstoneapplication.Seaborgium") -> return Seaborgium()
            ("com.example.capstoneapplication.Bohrium") -> return Bohrium()
            ("com.example.capstoneapplication.Hassium") -> return Hassium()
            ("com.example.capstoneapplication.Meitnerium") -> return Meitnerium()
            ("com.example.capstoneapplication.Darmstadtium") -> return Darmstadtium()
            ("com.example.capstoneapplication.Roentgenium") -> return Roentgenium()
            ("com.example.capstoneapplication.Copernicium") -> return Copernicium()
            ("com.example.capstoneapplication.Nihonium") -> return Nihonium()
            ("com.example.capstoneapplication.Flerovium") -> return Flerovium()
            ("com.example.capstoneapplication.Moscovium") -> return Moscovium()
            ("com.example.capstoneapplication.Livermorium") -> return Livermorium()
            ("com.example.capstoneapplication.Tennessine") -> return Tennessine()
            ("com.example.capstoneapplication.Oganesson") -> return Oganesson()
            else -> return null
        }
    }

    fun checknull(hash: HashMap<String?, Int?>, shell: String?): Int {
        if (hash.containsKey(shell)) {
            return hash.get(shell)!!
        } else return 0
    }
}
